---
title: "icu_cohort data analysis"
author: "Siyan Chen"
date: "Feb 28 2021"
---

## Introduction
This app is designed to interactively visualize MIMIC-IV database collected by MIT, which includes real hospital stays for patients admitted to a tertiary academic medical center in Boston, MA, USA.   
This application is available under an [MIT license](https://github.com/utah-dwq/LakeProfileDashboard/blob/master/LICENSE) .  
<br>

## Data
All data used by this application are available through [MIMIC IV](https://mimic-iv.mit.edu/docs/datasets/) .
MIMIC-IV contains comprehensive information for each patient while they were in the hospital: laboratory measurements, medications administered, vital signs documented, and so on. The database is intended to support a wide variety of research in healthcare. MIMIC-IV builds upon the success of MIMIC-III, and incorporates numerous improvements over MIMIC-III.

The icu_cohort,rds is an edited version of a combined database, which included all the information for the first ICU stay of each unique adult patient. Also, an indicator of whether the patient was dead within 30 days has been created and appended into the dataset.

## Application usage
The application has two main inputs: a map and a table. To build plots for any individual site, click on your desired site in either the map or the table.  

The map shows all sites with profile data available. The table shows all of those sites and their associated uses and assessments for each parameter.  

The map and table inputs are responsive to eachother. When you click a site on the map, the table will automatically filter to assessments associated with that site.
When you click on a row in the table, the map will automatically fly to that site location.  

Plots specific to that site will be rendered automatically. Several data plotting and review options are available.
Outputs will automatically render any time the user updates one of the input widgets.
<br>